name: Deploy to Azure Container App

on:
  workflow_dispatch:

env:
  # Azure Credential
  CONTAINER_REGISTRY: ${{ secrets.REGISTRY_URL }}

jobs:
  deploy-to-azure-container-app:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@master

      - name: Azure authentication
        uses: azure/actions/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR authentication
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: "Deploy to Azure Web App for Container"
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}
          resourceGroup: ${{ secrets.RESOURCE_GROUP }}
          imageToDeploy: ${{ env.CONTAINER_REGISTRY }}/myapp:${{ github.sha }}
          acrName: sdptestregistry
          acrUsername: ${{ secrets.REGISTRY_USERNAME }}
          acrPassword: ${{ secrets.REGISTRY_PASSWORD }}
          location: koreacentral
          containerAppName: sdp-test-app
