name: Deploy to Azure Container Registry

on: [push]

env:
  CONTAINER_REGISTRY: ${{ secrets.REGISTRY_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Azure authentication
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
    - name: ACR authentication
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.CONTAINER_REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Docker Build & push to ACR
      run: |
        docker build . -t ${{ env.CONTAINER_REGISTRY }}/myapp:${{ github.sha }}
        docker push ${{ env.CONTAINER_REGISTRY }}/myapp:${{ github.sha }}
        
    - name: 'Deploy to Azure Web App for Container'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sdptestapp'
        images: ${{ env.CONTAINER_REGISTRY }}/myapp:${{ github.sha }}
